name: Release Package

# This action will start when a correctly formatted tag is pushed (e.g. 0.1.0)

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+(-.+)?"

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
    - name: Build ImageSharp Package
      run: dotnet build src\ImageSharp.Community.Providers.Remote\ImageSharp.Community.Providers.Remote.csproj --configuration Release
  
    - name: Build Umbraco Package
      run: dotnet build src\Umbraco.Community.ImageSharpRemoteImages\Umbraco.Community.ImageSharpRemoteImages.csproj --configuration Release

    - name: Push to NuGet
      run: dotnet nuget push **\*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
